# Generated by Django 4.0.2 on 2022-03-06 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.IntegerField()),
                ('date', models.DateTimeField(verbose_name='date_added')),
            ],
        ),
        migrations.CreateModel(
            name='ExpDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.TextField(max_length=400)),
                ('expenses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.expenses')),
            ],
        ),
    ]
