# Generated by Django 4.0.2 on 2022-03-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expdetails',
            name='pub_data',
            field=models.DateTimeField(default=None, verbose_name='pub_date'),
        ),
    ]
